[package]
name = "adam"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
serde = "1.0"
csv = "1.2"
regex = "1.12"
twitter-v2 = "0.1"
rand = "0.9.2"
